/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Signer, utils, Contract, ContractFactory, Overrides } from "ethers";
import { Provider, TransactionRequest } from "@ethersproject/providers";
import type { DutchAuction, DutchAuctionInterface } from "../DutchAuction";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
      {
        internalType: "bytes",
        name: "",
        type: "bytes",
      },
      {
        internalType: "address",
        name: "",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
      {
        internalType: "address",
        name: "",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    name: "canBid",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "pure",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "deadline",
        type: "uint256",
      },
      {
        internalType: "bytes",
        name: "params",
        type: "bytes",
      },
      {
        internalType: "address",
        name: "",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "bidPrice",
        type: "uint256",
      },
      {
        internalType: "address",
        name: "",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    name: "canClaim",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

const _bytecode =
  "0x608060405234801561001057600080fd5b506103ad806100206000396000f3fe608060405234801561001057600080fd5b50600436106100365760003560e01c8063610e2d3b1461003b578063e9b3838f14610062575b600080fd5b61004e6100493660046101c4565b61007e565b604051901515815260200160405180910390f35b61004e6100703660046101c4565b600098975050505050505050565b6000806000808980602001905181019061009891906102c8565b9250925092508183116100f25760405162461bcd60e51b815260206004820152601a60248201527f53484f59553a20494e56414c49445f50524943455f52414e474500000000000060448201526064015b60405180910390fd5b8a81106101415760405162461bcd60e51b815260206004820152601960248201527f53484f59553a20494e56414c49445f535441525445445f41540000000000000060448201526064016100e9565b600061014d828d610334565b6101578486610334565b61016191906102f5565b90506000816101708442610334565b61017a9190610315565b6101849086610334565b90508c42111580156101965750808a10155b9e9d5050505050505050505050505050565b80356001600160a01b03811681146101bf57600080fd5b919050565b600080600080600080600080610100898b0312156101e0578384fd5b6101e9896101a8565b975060208901359650604089013567ffffffffffffffff8082111561020c578586fd5b818b0191508b601f83011261021f578586fd5b81358181111561023157610231610361565b604051601f8201601f19908116603f0116810190838211818310171561025957610259610361565b816040528281528e6020848701011115610271578889fd5b8260208601602083013791820160200188905250975061029691505060608a016101a8565b9450608089013593506102ab60a08a016101a8565b925060c0890135915060e089013590509295985092959890939650565b6000806000606084860312156102dc578283fd5b8351925060208401519150604084015190509250925092565b60008261031057634e487b7160e01b81526012600452602481fd5b500490565b600081600019048311821515161561032f5761032f61034b565b500290565b6000828210156103465761034661034b565b500390565b634e487b7160e01b600052601160045260246000fd5b634e487b7160e01b600052604160045260246000fdfea26469706673582212208bfac71fb9033ae793233da3094d6d78e2d8346dad47710cecc41bfaf100dec064736f6c63430008030033";

export class DutchAuction__factory extends ContractFactory {
  constructor(signer?: Signer) {
    super(_abi, _bytecode, signer);
  }

  deploy(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<DutchAuction> {
    return super.deploy(overrides || {}) as Promise<DutchAuction>;
  }
  getDeployTransaction(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): TransactionRequest {
    return super.getDeployTransaction(overrides || {});
  }
  attach(address: string): DutchAuction {
    return super.attach(address) as DutchAuction;
  }
  connect(signer: Signer): DutchAuction__factory {
    return super.connect(signer) as DutchAuction__factory;
  }
  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): DutchAuctionInterface {
    return new utils.Interface(_abi) as DutchAuctionInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): DutchAuction {
    return new Contract(address, _abi, signerOrProvider) as DutchAuction;
  }
}
