/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Signer, utils, Contract, ContractFactory, Overrides } from "ethers";
import { Provider, TransactionRequest } from "@ethersproject/providers";
import type { Orders, OrdersInterface } from "../Orders";

const _abi = [
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "c__0x6fa5afeb",
        type: "bytes32",
      },
    ],
    name: "c_0x6fa5afeb",
    outputs: [],
    stateMutability: "pure",
    type: "function",
  },
];

const _bytecode =
  "0x60e0610052600b82828239805160001a607314610045577f4e487b7100000000000000000000000000000000000000000000000000000000600052600060045260246000fd5b30600052607381538281f3fe730000000000000000000000000000000000000000301460806040526004361060335760003560e01c8063c0531acd146038575b600080fd5b604e6004803603810190604a91906066565b6050565b005b50565b6000813590506060816096565b92915050565b600060208284031215607757600080fd5b60006083848285016053565b91505092915050565b6000819050919050565b609d81608c565b811460a757600080fd5b5056fea2646970667358221220695875cecd3764820746ed1c2d8fc922594ca5f772d4eaa5d65b115ed38ceb1464736f6c63430008030033";

export class Orders__factory extends ContractFactory {
  constructor(signer?: Signer) {
    super(_abi, _bytecode, signer);
  }

  deploy(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<Orders> {
    return super.deploy(overrides || {}) as Promise<Orders>;
  }
  getDeployTransaction(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): TransactionRequest {
    return super.getDeployTransaction(overrides || {});
  }
  attach(address: string): Orders {
    return super.attach(address) as Orders;
  }
  connect(signer: Signer): Orders__factory {
    return super.connect(signer) as Orders__factory;
  }
  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): OrdersInterface {
    return new utils.Interface(_abi) as OrdersInterface;
  }
  static connect(address: string, signerOrProvider: Signer | Provider): Orders {
    return new Contract(address, _abi, signerOrProvider) as Orders;
  }
}
