/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Signer, utils, Contract, ContractFactory, Overrides } from "ethers";
import { Provider, TransactionRequest } from "@ethersproject/providers";
import type { Signature, SignatureInterface } from "../Signature";

const _abi = [
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "c__0x2d3da901",
        type: "bytes32",
      },
    ],
    name: "c_0x2d3da901",
    outputs: [],
    stateMutability: "pure",
    type: "function",
  },
];

const _bytecode =
  "0x60e0610052600b82828239805160001a607314610045577f4e487b7100000000000000000000000000000000000000000000000000000000600052600060045260246000fd5b30600052607381538281f3fe730000000000000000000000000000000000000000301460806040526004361060335760003560e01c8063a3a9d629146038575b600080fd5b604e6004803603810190604a91906066565b6050565b005b50565b6000813590506060816096565b92915050565b600060208284031215607757600080fd5b60006083848285016053565b91505092915050565b6000819050919050565b609d81608c565b811460a757600080fd5b5056fea26469706673582212207fa3caba7eca6decda23670ada3ad69fc4715ee4bd659e4c5ee884c6680f306464736f6c63430008030033";

export class Signature__factory extends ContractFactory {
  constructor(signer?: Signer) {
    super(_abi, _bytecode, signer);
  }

  deploy(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<Signature> {
    return super.deploy(overrides || {}) as Promise<Signature>;
  }
  getDeployTransaction(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): TransactionRequest {
    return super.getDeployTransaction(overrides || {});
  }
  attach(address: string): Signature {
    return super.attach(address) as Signature;
  }
  connect(signer: Signer): Signature__factory {
    return super.connect(signer) as Signature__factory;
  }
  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): SignatureInterface {
    return new utils.Interface(_abi) as SignatureInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): Signature {
    return new Contract(address, _abi, signerOrProvider) as Signature;
  }
}
